## minecraft-server config
server:
  memory: 8162M
  port: 25565

## tunnel config
tunnel:
  serveo: false
    hostname: serveo.net
    port: <PORTNUMBER>

  connect: true
    token: <TOKEN>
    endpoint: <NAME>
    hostname: play.minekube.net

## dns config
dns:
  dsec: false
    token:

  dynv6: false
    token: <TOKEN>
    zones: <DNSZONENAME>